hostname: jenkins
# Docker config


# nginx config
nginx: true
cert_name: home-local.site
email: vladoz77@yandex.ru
certbot_renew_minutes: 0
certbot_renew_hours: 0
domains:
- "{{ jenkins_url_address }}"
- "{{ sonarqube_url_address }}"
- "{{ nexus_url_address }}"
- "{{ registry_url_address }}"
# Jenkins config
jenkins: true
jenkins_url_address: jenkins.home-local.site
# Sonarqube
sonarqube: true
sonarqube_url_address: sonarqube.home-local.site
# Nexus
nexus: true
nexus_url_address: nexus.home-local.site
registry_url_address: registry.home-local.site
repo_name: docker-hosted
repo_port: 8082
