hostname: jenkins
# Docker config
docker_network_name: extra_network

# TLS config
cert_name: home-local.site
email: vladoz77@yandex.ru
certbot_renew_minutes: 0
certbot_renew_hours: 0
domains:
- "{{ jenkins_url_address }}"
- "{{ sonarqube_url_address }}"
- "{{ nexus_url_address }}"
- "{{ registry_url_address }}"
# Jenkins config
jenkins_url_address: jenkins.home-local.site
# Sonarqube
sonarqube: true
sonarqube_url_address: sonarqube.home-local.site
# Nexus
nexus: true
nexus_url_address: nexus.home-local.site
registry_url_address: registry.home-local.site 

site_available_dir: /etc/nginx/sites-available
site_enabled_dir: /etc/nginx/sites-enabled