hostname: jenkins
sysctl_params:
- key: net.ipv4.ip_forward
  value: 1
- key: vm.max_map_count
  value: 262144
# Jenkins config
jenkins_url_address: jenkins.home.local
jenkins_plugin_list:
- ant:latest
- antisamy-markup-formatter:latest
- build-timeout:latest
- cloudbees-folder:latest
- configuration-as-code:latest
- credentials-binding:latest
- email-ext:latest
- git:latest
- github-branch-source:latest
- gradle:latest
- ldap:latest
- mailer:latest
- matrix-auth:latest
- pam-auth:latest
- pipeline-github-lib:latest
- pipeline-stage-view:latest
- ssh-slaves:latest
- timestamper:latest
- workflow-aggregator:latest
- ws-cleanup:latest
- adoptopenjdk:1.7
- sonar:latest

maven_enable: true
java_enable: true
sonarqube: true
sonarqube_url: "http://localhost:9090"
sonarqube_url_address: sonarqube.home.local
