jenkins_docker_dir: "/home/{{ ansible_user }}/{{ jenkins_container_name }}"
jenkins_base_files:
- docker-compose.yaml
- jenkins.yaml
- Dockerfile
- plugins.txt
- nexus.groovy

jenkins_nexus_files:
- nexus.groovy