container_name: jenkins
jenkins_home: /var/jenkins_home
jenkins_docker_dir: "/home/{{ username }}/jenkins"
jenkins_install_file:
- docker-compose.yaml
- jenkins.yaml
- Dockerfile
- plugins.txt
site_available_dir: /etc/nginx/sites-available
site_enabled_dir: /etc/nginx/sites-enabled