---
- name: Wait for cloud-init to finish on all nodes
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Wait for cloud-init completion
      command: cloud-init status --wait --long
      become: yes

- name: Common configuration for all nodes
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - common-config

- name: Configure master nodes
  hosts: master
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: ha-master-config
      when: ha_enabled 
    - role: master-config
      when: inventory_hostname == groups['master'][0]
    - role: join-master
      when: ha_enabled 

- name: Configure worker nodes
  hosts: worker
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - join-worker