# k8s-install-all.yaml
- name: Common configuration for all nodes
  hosts: all
  become: true
  gather_facts: false
  roles:
  - k8s-common-config

- name: Configure master nodes
  hosts: master
  become: true
  roles:
  - role: k8s-ha-master-config
    when: ha_enabled
  - role: k8s-config-master
    when: inventory_hostname == groups['master'][0]
  - role: k8s-join-master
    when: ha_enabled

- name: Configure worker nodes
  hosts: worker
  become: true
  roles:
  - k8s-join-worker
