# docker config
docker_network_name: "bridge"
traefik_container_name: traefik
traefik_image: "traefik"
traefik_version: "v3.5"
traefik_docker_dir: "/home/{{ ansible_user }}/{{ traefik_container_name }}"
# Dashboard config
traefik_enable_dashboard: true
traefik_dashboard_url: "{{ traefik_container_name }}.{{ domain_name | default('home.local')}}"
traefik_dashboard_user: "admin"
traefik_dashboard_password_hash: "$$apr1$$CmiVRFjs$$bPQcSgQ.2HcTzM.HVTvAl1"  # admin:admin
# Acme config
domain_name: "yc.home-local.site"
acme_email: "vladoz77@yandex.ru"
traefik_letsencrypt_path: "{{ traefik_docker_dir }}/letsencrypt"