- name: check if runing {{ sonarqube_container_name }} in docker
  community.docker.docker_container_info:
    name: "{{ sonarqube_container_name }}"
  register: container_status
  ignore_errors: true
   
- name: install SonarQube with docker
  ansible.builtin.include_tasks: sonar-install.yaml
  when: container_status.exists == false or container_status.container.State.Running == false

- name: Wait for SonarQube to become available
  ansible.builtin.uri:
    url: "{{ sonarqube_url }}/api/system/status"
    method: GET
    status_code: 200
    body_format: json
  register: sonar_status
  until: sonar_status.status == 200 and sonar_status.json.status == "UP"
  retries: 60
  delay: 10
  ignore_errors: yes

- name: config user and token in sonarqube
  ansible.builtin.include_tasks: sonar-config.yaml
  # when: 
  #  - 
  #  - sonarqube_token_name not in (token_status.get('json', {}).get('userTokens', []) | map(attribute='name') | list) 