- name: set "{{ item.key }}" to "{{ item.value}}"
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    state: present
    value: "{{ item.value}}"
    reload: true
  loop: "{{ sysctl_params }}"


- name: check if runing {{ container_name }} in docker
  community.docker.docker_container_info:
    name: "{{ container_name }}"
  register: container_status
  ignore_errors: true
   
- name: install {{ container_name }} with docker
  ansible.builtin.include_tasks: "{{ container_name }}-install.yaml"
  when: container_status.exists == false or container_status.container.State.Running == false

- name: Wait for {{ container_name }} to become available
  ansible.builtin.uri:
    url: "{{ sonarqube_url }}/api/system/status"
    method: GET
    status_code: 200
    body_format: json
  register: sonar_status
  until: sonar_status.status == 200 and sonar_status.json.status == "UP"
  retries: 60
  delay: 10
  ignore_errors: yes

- name: config user and token in {{ container_name }}
  ansible.builtin.include_tasks: "{{ container_name }}-config.yaml"

