- name: Get containers using port 80 or 443
  ansible.builtin.command: docker container ls -q --filter publish=80 --filter publish=443
  register: containers_to_remove
  ignore_errors: true

- name: Stop and remove any container using port 80 or 443
  community.docker.docker_container:
    name: "{{ item }}"
    state: absent
  loop: "{{ containers_to_remove.stdout_lines }}"
  when: containers_to_remove.stdout_lines | length > 0

- name: Create folder traefik
  ansible.builtin.file:
    path: "{{ traefik_docker_dir }}"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    state: directory

- name: Copy template to {{ traefik_docker_dir }}
  ansible.builtin.template:
    src: "templates/docker-compose-traefik.yaml.j2"
    dest: "{{ traefik_docker_dir }}/docker-compose.yaml"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"

- name: start traefik
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_docker_dir }}"
    recreate: always
    state: present
