- name: install jenkins
  hosts: jenkins
  become: true
  pre_tasks:
  - name: add hostname
    ansible.builtin.hostname:
      name: "{{ hostname }}"

  - name: install req soft
    ansible.builtin.apt:
      name: "{{ soft }}"
      state: present
      update_cache: true
  
  tasks:
  - name: install nginx
    ansible.builtin.include_role:
      name: nginx

  - name: install docker
    ansible.builtin.include_role:
      name: docker

  - name: install sonarqube
    ansible.builtin.include_role:
      name: sonarqube
    when: sonarqube == true

  - name: install jenkins
    ansible.builtin.include_role:
      name: jenkins
