- name: install jenkins-agent
  hosts: jenkins-agent
  become: true
  pre_tasks:
    - name: Gather facts 
      setup:

    - name: add hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
    
    - name: install base soft
      ansible.builtin.apt:
        name: "{{ soft }}"
        state: present
        update_cache: true
  tasks:

  - name: Generate ssh key
    community.crypto.openssh_keypair:
      path: "{{ ssh_dir }}/{{ agent_ssh_key }}"
      size: 2048
      type: ed25519
      owner: "{{ username }}"
      group: "{{ username }}"
      force: true

  - name: copy ssh pub key to autorize
    ansible.builtin.shell: cat {{ ssh_dir }}/{{ agent_ssh_key }}.pub >> {{ ssh_dir }}/authorized_keys

  - name: install docker
    ansible.builtin.include_role:
      name: docker

  - name: install trivy
    ansible.builtin.include_role: 
      name: trivy
    when: trivy == true
      