
- name: install jenkins-agent
  hosts: jenkins-agent
  become: true
  tasks:
  
  - name: add hostname
    ansible.builtin.hostname:
      name: "{{ hostname }}"

  - name: Generate ssh key
    community.crypto.openssh_keypair:
      path: "{{ ssh_dir }}/{{ agent_ssh_key }}"
      size: 2048
      type: ed25519
      owner: "{{ username }}"
      group: "{{ username }}"
      force: true

  - name: copy ssh pub key to autorize
    ansible.builtin.shell: 
      cat {{ ssh_dir }}/{{ agent_ssh_key }}.pub >> {{ ssh_dir }}/authorized_keys

  - name: install base soft
    ansible.builtin.apt:
      name: "{{ soft }}"
      state: present
      update_cache: true

  - name: Check if trivy is installed
    command: dpkg-query -W trivy
    register: trivy_deb
    failed_when: trivy_deb.rc > 1
    changed_when: trivy_deb.rc == 1

  - name: install trivy scaner
    block:
    - name: download trivi
      ansible.builtin.uri:
        url: "{{ trivi_url }}"
        dest: /tmp/trivy.deb

    - name: install trivi from deb
      ansible.builtin.apt:
        deb: /tmp/trivy.deb

    - name: delete file
      ansible.builtin.file:
        path: /tmp/trivy.deb
        state: absent

    when: trivy_deb.rc == 1

  - name: install docker
    ansible.builtin.include_role:
      name: docker
  
- name: Copy SSH private key from jenkins-agent to jenkins using fetch
  hosts: localhost
  become: false
  vars:
    username: "{{ hostvars[groups['jenkins'][0]]['username'] }}"
  tasks:
    - name: Fetch SSH private key from jenkins-agent
      ansible.builtin.fetch:
        src: "{{ ssh_dir }}/{{ agent_ssh_key }}"
        dest: "{{ agent_ssh_tmp_key }}"
        flat: yes
      delegate_to: "{{ groups['jenkins-agent'][0] }}"

    - name: Copy fetched SSH private key to jenkins
      ansible.builtin.copy:
        src: "{{ agent_ssh_tmp_key }}"
        dest: "{{ ssh_dir }}/{{ agent_ssh_key }}"
        # owner: "{{ username }}"
        # group: "{{ username }}"
        mode: '0600'
      delegate_to: "{{ groups['jenkins'][0] }}"

    - name: Clean up temporary file
      ansible.builtin.file:
        path: "/tmp/fetched_key"
        state: absent




- name: install jenkins
  hosts: jenkins
  become: true
  tasks:
  - name: add hostname
    ansible.builtin.hostname:
      name: "{{ hostname }}"

  - name: install docker
    ansible.builtin.include_role:
      name: docker

  - name: install jenkins
    ansible.builtin.include_role:
      name: jenkins
      

  

  