- name: create folder jenkins
  ansible.builtin.file:
    path: "{{ jenkins_docker_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: Read token from fetched file
  ansible.builtin.slurp:
    src: "/tmp/sonar_token.txt"
  register: token_data

- name: Set token as variable
  ansible.builtin.set_fact:
    sonar_token: "{{ token_data.content | b64decode }}"

- name: Debug token
  ansible.builtin.debug:
    msg: "Sonar Token: {{ sonar_token }}"

- name: Copy templates to {{ jenkins_docker_dir }}
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "{{ jenkins_docker_dir }}/{{ item }}"
    group: "{{ username }}"
    owner: "{{ username }}"
  loop: "{{ jenkins_install_file }}"

- name: start docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ jenkins_docker_dir }}"
    recreate: always
    remove_volumes: true
    state: present
