- name: create folder jenkins
  ansible.builtin.file:
    path: "{{ jenkins_docker_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: Copy templates to {{ jenkins_docker_dir }}
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "{{ jenkins_docker_dir }}/{{ item }}"
    group: "{{ username }}"
    owner: "{{ username }}"
  loop: "{{ jenkins_install_file }}"

- name: start docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ jenkins_docker_dir }}"
    state: present
