- name: check status jenkins-agent
  ansible.builtin.systemd:
    name: "{{ jenkins_agent_service_name }}"
    enabled: yes
  register: agent_service
  when: service_file.stat.exists

- block:
  - name: create agent folder
    ansible.builtin.file:
      path: "{{ agent_work_dir }}"
      group: "{{ ansible_user }}"
      owner: "{{ ansible_user }}"
      state: directory

  - name: download agent
    ansible.builtin.uri:
      url: "{{ jenkins_agent_download_url }}"
      dest: /usr/local/bin

  - name: copy service template
    ansible.builtin.template:
      src: jenkins-agent.service.j2
      dest: "{{service_dir}}/{{ jenkins_agent_service_name }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: start jenkins-agent
    ansible.builtin.systemd:
      name: "{{ jenkins_agent_service_name }}"
      state: started
      daemon_reload: true
      enabled: true
  when: not service_file.stat.exists or (service_file.stat.exists and agent_service.status.ActiveState != "active")