- name: copy jenkins-api-token
  ansible.builtin.copy:
    src: "{{ default_token_dir }}"
    dest: /tmp/agent-api-token.txt
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: default_token_dir is defined

- name: read jagent-api-token.txt
  ansible.builtin.slurp:
    src: /tmp/agent-api-token.txt
  register: api_token_file

- name: set api_token
  ansible.builtin.set_fact:
    api_token: "{{ api_token_file.content | b64decode }}"
  when:
  - api_token_file is defined
  - api_token_file.content | length > 0

- ansible.builtin.debug:
    msg: "https:{{ jenkins_url }}/computer/agent-{{ inventory_hostname }}/slave-agent.jnlp"

- name: get secret from jenkins
  ansible.builtin.uri:
    url: "https://{{ jenkins_url }}/computer/agent-{{ inventory_hostname }}/slave-agent.jnlp"
    user: "{{ jenkins_username }}"
    password: "{{ api_token }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    status_code: 200
  register: jnlp_response
  when: api_token is defined or jenkins_password is defined

- name: extract secret from JNLP jnlp response
  ansible.builtin.set_fact:
    agent_secret: "{{ jnlp_response.content  | regex_search('<argument>([a-z0-9]+)</argument>', '\\1') | first }}"
  when:
  - jnlp_response is defined

