- name: Validate jenkins_agent_state variable
  ansible.builtin.assert:
    that:
      - jenkins_agent_state in ['enabled', 'disabled']
    msg: "jenkins_agent_state must be 'enabled' or 'disabled'"
  no_log: true

- name: check if service file exist
  ansible.builtin.stat:
    path:  "{{ service_dir }}/{{ jenkins_agent_service_name }}"
  register: service_file

- block:
  - name: get secret
    ansible.builtin.include_tasks:
      get-secret.yaml

  - name: add-agent
    ansible.builtin.include_tasks: add-agent.yaml
    when: 
      - not service_file.stat.exists
  when: 
   - jenkins_agent_state == "enabled"


- name: unninstall jenkins-agent  
  ansible.builtin.include_tasks:
    unninstall-agent.yaml
  when: 
   - jenkins_agent_state == "disabled"
   - service_file.stat.exists