- name: check if runing {{ container_name }} in docker
  community.docker.docker_container_info:
    name: "{{ container_name }}"
  register: container_status
  ignore_errors: true

- name: install {{ container_name }} with docker
  ansible.builtin.include_tasks: "{{ container_name }}-install.yaml"
  when: container_status.exists == false or container_status.container.State.Running == false

