- name: Wait for {{ container_name}} to become available
  ansible.builtin.uri:
      url: "{{ nexus_url }}/{{ status_check }}"
      method: GET
      status_code: 200
  register: nexus_status
  until: nexus_status.status == 200 
  retries: 30
  delay: 10
  ignore_errors: yes

- name: Check users list with new password
  ansible.builtin.uri:
    url: "{{ nexus_url }}/service/rest/v1/security/users"
    method: GET
    user: "{{ admin_user }}"
    password: "{{ vault_secrets.new_admin_password }}"
    force_basic_auth: yes
    status_code: 
    - 200
    - 400
    - 403
    - 401
    validate_certs: no
  register: nexus_users_check
  ignore_errors: true

- name: Change default admin password
  block:
  - name: Get old password in {{ container_name }}
    community.docker.docker_container_exec:
      container: "{{ container_name }}"
      command: /bin/bash -c "cat /nexus-data/admin.password"
    register: default_pass

  - name: set old password
    ansible.builtin.set_fact:
      default_password: "{{ default_pass.stdout }}"

  - name: Change old password
    ansible.builtin.uri:
      method: PUT
      url: "{{ nexus_url }}/{{ change_password }}"
      url_username: "{{ admin_user }}"
      url_password: "{{ default_password }}"
      force_basic_auth: yes
      headers:
        Content-Type: "text/plain"
      body: "{{ vault_secrets.new_admin_password }}"
      status_code: 204

  when: nexus_users_check.status != 200
  
- name: check if role {{ role_id }} exist
  ansible.builtin.uri:
    url: "{{ nexus_url }}/{{ get_role }}/{{ role_id }}?source=default"
    method: GET
    url_username: "{{ admin_user }}"
    url_password: "{{ vault_secrets.new_admin_password }}"
    force_basic_auth: yes
    status_code:
      - 200
      - 404
  register: role_result

- ansible.builtin.debug:
    msg: "Role {{ role_id }} already exist in Nexus"
  when: role_result.status == 200

- name: create new role
  ansible.builtin.uri:
    url: "{{ nexus_url }}/{{ create_role }}"
    method: POST
    headers:
        Content-Type: "application/json"
    url_username: "{{ admin_user }}"
    url_password: "{{ vault_secrets.new_admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: 
      id: "{{ role_id }}"
      name: "Docker Read/Edit Access"
      description: "Allows read and edit access to Docker repositories"
      privileges:
        - "nx-repository-view-docker-*-add"
        - "nx-repository-view-docker-*-browse"
        - "nx-repository-view-docker-*-edit"
        - "nx-repository-view-docker-*-read"
      roles: []
    status_code:
      - 200
  when: role_result.status == 404

- name: check if {{ nexus_username }} exist
  ansible.builtin.uri:
    url: "{{ nexus_url }}/{{ get_user }}"
    method: GET
    url_username: "{{ admin_user }}"
    url_password: "{{ vault_secrets.new_admin_password }}"
    force_basic_auth: yes
    status_code:
      - 200
      - 404
  register: user_result

- ansible.builtin.set_fact:
    user_exist: "{{ user_result.json | selectattr('userId', 'equalto', nexus_username) | map(attribute = 'userId'  ) | list | length > 0 }}"

- ansible.builtin.debug:
    msg: "User {{ nexus_username }} already exist in Nexus"
  when: user_exist

- name: Create user
  ansible.builtin.uri:
    url: "{{ nexus_url }}/{{ create_user }}"
    method: POST
    headers:
        Content-Type: "application/json"
    url_username: "{{ admin_user }}"
    url_password: "{{ vault_secrets.new_admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: 
      userId: "{{ nexus_username }}"
      firstName: "{{ nexus_username }}"
      lastName: "{{ nexus_username }}"
      emailAddress: "{{ nexus_username }}@example.com"
      password: "{{ vault_secrets.nexus_password }}"
      status: "active"
      roles:
        - "{{ role_id }}"
    status_code:
      - 200
      - 403
      - 400
  when: not user_exist

- name: Check if repo {{ repo_name }} if exist
  ansible.builtin.uri:
    url: "{{ nexus_url }}/{{ get_repo }}/{{ repo_name }}"
    method: GET
    url_username: "{{ admin_user }}"
    url_password: "{{ vault_secrets.new_admin_password }}"
    force_basic_auth: yes
    status_code:
      - 200
      - 404
  register: repo_result

- ansible.builtin.debug:
    msg: "Repo {{ repo_name }} already exist in Nexus"
  when: repo_result.status == 200

- name: Create repositories
  ansible.builtin.uri:
    url: "{{ nexus_url }}/{{ create_repo_hosted }}"
    method: POST
    headers:
        Content-Type: "application/json"
    url_username: "{{ admin_user }}"
    url_password: "{{ vault_secrets.new_admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: 
      name: "{{ repo_name }}"
      online: true
      storage:
        blobStoreName: "default"
        strictContentTypeValidation: true
        writePolicy: "allow_once"
        latestPolicy: true
      cleanup:
        policyNames: []
      component:
        proprietaryComponents: true
      docker:
        v1Enabled: true
        forceBasicAuth: true
        httpPort: "{{ repo_port }}"
        subdomain: docker-a
    status_code:
      - 201
      - 401
      - 403
  when: repo_result.status == 404
    

