- name: check if runing {{ nexus_container_name }} in docker
  community.docker.docker_container_info:
    name: "{{ nexus_container_name }}"
  register: container_status
  ignore_errors: true

- ansible.builtin.debug:
    msg: "{{ nexus_container_name }} exist and running"
  when: container_status.exists and container_status.container.State.Running 

- name: install {{ nexus_container_name }} with docker
  ansible.builtin.include_tasks: "{{ nexus_container_name }}-install.yaml"
  when: not container_status.exists  or  not container_status.container.State.Running

- name: Config {{ nexus_container_name }} 
  ansible.builtin.include_tasks: "{{ nexus_container_name }}-config.yaml"
    