container_name: sonarqube
sonarqube_docker_dir: "/home/{{ username }}/{{ container_name }}"
sonarqube_url: http://localhost:9090
sonarqube_default_admin_password: admin
sonarqube_admin_password: "!QAZ2wsx#EDC4rfv"
sonarqube_user: "{{ container_name }}"
sonarqube_password: "{{ container_name }}"
sonarqube_user_group: sonar-administrators
sonarqube_token_name: token
sonarqube_jenkins_webhook_name: jenkins-webhook
sonaqube_jenkins_webhook_url: https://{{ jenkins_url_address }}/sonarqube-webhook