- name: copy config file
  ansible.builtin.template:
    src: templates/{{ jenkins_url_address}}.j2
    dest: "{{ site_available_dir}}/{{ jenkins_url_address}}"

- name: enable site
  ansible.builtin.file:
    src: "{{ site_available_dir}}/{{ jenkins_url_address}}"
    dest: "{{ site_enabled_dir  }}/{{ jenkins_url_address}}"
    state: link
  notify: nginx-restart

- name: start handler force
  meta: flush_handlers
