- name: Install nginx
  ansible.builtin.include_tasks:  install-nginx.yaml

- name: check existing certificate
  ansible.builtin.stat:
    path: "{{ cert_dir }}/live/{{ cert_name }}/cert.pem"
  register: certbot_stat

- name: Create certificate wuth certbot
  ansible.builtin.include_tasks: certbot.yaml
  when: certbot_stat.stat.exists == false

- name: Config ssl in nginx
  ansible.builtin.include_tasks: config-ssl.yaml
    
- name: add nginx config for nexus
  ansible.builtin.include_tasks: "nexus-nginx.yaml"
  when: nexus == true

- name: add nginx config for sonarqube
  ansible.builtin.include_tasks: "sonarqube-nginx.yaml"
  when: sonarqube == true

- name: add nginx config for jenkins
  ansible.builtin.include_tasks: "jenkins-nginx.yaml"
  when: jenkins == true