def terraform(terraform_dir) {
    dir(terraform_dir) {
        if (params.terraform_action == 'apply') {
            sh"""
            terraform init
            terraform apply -auto-approve
            """
        } else if (params.terraform_action == 'destroy'){
            sh"""
            terraform init
            terraform destroy -auto-approve
            """
        }
    }
}

pipeline {
    agent any

    parameters {
        choice choices: ['apply', 'destroy'], description: 'Terraform action', name: 'terraform_action'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/vladoz77/terraform.git'
            }
        }

        stage('Terraform Apply or Destroy') {
            steps {
                script {
                    terraform('lxd-k8s/terraform/infrastucture')
                }
            }
        }

        stage('Configure Kubernetes with Ansible') {
            when {
                expression {params.terraform_action == 'apply'}
            }
            steps {
                script {
                    echo "Installing ansible dependences..."
                    dir('lxd-k8s/ansible'){
                        sh 'ansible-galaxy collection install -r requirements.yaml'
                    }
                    echo "Instaling k8s..."
                    ansiblePlaybook credentialsId: 'vlad-ssh-key',
                        disableHostKeyChecking: true, 
                        installation: 'ansible', 
                        inventory: 'lxd-k8s/ansible/inventory.ini', 
                        playbook: 'lxd-k8s/ansible/install-k8s.yaml'
                }
            }
        }

        stage('Install or destroy base k8s applications'){
            when {
                expression { params.terraform_action == 'apply' }
            }
            steps {
                script{
                    terraform('lxd-k8s/terraform/k8s-applications')
                }
            }
        }
    }
}