- name: Config jenkins server
  hosts: jenkins-server
  become: true
  roles:
    - common
    - docker
    - traefik
    - nexus
    - jenkins

- name: Config agent 
  hosts: jenkins-agent
  become: true
  vars:
    jenkins_agent_state: enabled
  roles:
    - common
    - docker
    - add-agent