- name: Config jenkins server
  hosts: jenkins-server
  become: true
  vars:
    jenkins_url: jenkins.home-local.site
    acme_email: vladozz23@gmail.com
    traefik_docker_dir: /home/{{ ansible_user }}/traefik
    s3_bucket_name: acme-bucket
  roles:
    - common
    - docker
    - traefik
    - jenkins
    - sync_acme_to_s3
