- name: Config jenkins server
  hosts: jenkins-server
  become: true
  vars:
    jenkins_url: jenkins.home-local.site
    s3_bucket_name: acme-bucket
  roles:
    - common
    - docker
    - traefik
    - jenkins
    - sync_acme_to_s3
