#cloud-config
users:
- name: ubuntu
  sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
  shell: /bin/bash
  ssh_authorized_keys:
  - "ssh-rsa AAAA...REPLACE_WITH_YOUR_PUBLIC_KEY... user@example"

package_update: true
packages:
- curl
- ca-certificates
- apt-transport-https

runcmd:
- [ sh, -c, 'apt-get update && apt-get -y upgrade' ]
- [ sh, -c, 'apt-get -y install docker.io' ]
- [ sh, -c, 'systemctl enable --now docker' ]
