- name: Check container status
  community.docker.docker_container_info:
    name: "{{ jenkins_container_name }}"
  register: container_info
  until: 
    - container_info is not failed
    - container_info.container.State.Status == "running"
    - container_info.container.State.Health.Status == "healthy"
  retries: 30
  delay: 10
  ignore_errors: yes


- name: Generate Jenkins API token via curl (shell)
  ansible.builtin.shell: |
    # Получаем crumb через /api/xml (работает даже без полной сессии)
    RESPONSE=$(curl -k -s \
      -u "{{ jenkins_username }}:{{ jenkins_password }}" \
      -c /tmp/jenkins_cookies.txt \
      "https://{{ jenkins_url }}/crumbIssuer/api/xml")
    
    # Извлекаем поля
    CRUMB_FIELD=$(echo "$RESPONSE" | grep -oP '<crumbRequestField>\K[^<]+')
    CRUMB_VALUE=$(echo "$RESPONSE" | grep -oP '<crumb>\K[^<]+')
    
    # Формируем заголовок (без кавычек!)
    CRUMB_HEADER="$CRUMB_FIELD: $CRUMB_VALUE"
    
    # Генерируем токен
    curl -k -s \
      -u "{{ jenkins_username }}:{{ jenkins_password }}" \
      -b /tmp/jenkins_cookies.txt \
      -H "$CRUMB_HEADER" \
      -H "Content-Type: application/x-www-form-urlencoded" \
      --data "newTokenName=ansible-shell-token" \
      "https://{{ jenkins_url }}/user/{{ jenkins_username }}/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken" \
      | jq -r '.data.tokenValue'

  register: token_result
  changed_when: false
  no_log: false
  when: 
    - container_info is not failed
    - container_info.container.State.Status == "running"
    - container_info.container.State.Health.Status == "healthy"

- name: Save API token as fact on control node
  ansible.builtin.copy:
    content: "{{ token_result.stdout }}"
    dest: "{{ default_token_dir }}"
    mode: 0600
  delegate_to: localhost
  become: false
  when: 
    - token_result is defined
    - token_result.stdout | length > 0
