- name: Set timezone
  community.general.timezone:
    name: Europe/Moscow

- name: Create user
  ansible.builtin.user:
    name: "{{ username }}"
    groups: wheel
    password: "{{ password | password_hash('sha512') }}"
    shell: /bin/bash
    state: present

- name: Add ssh keys
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '/home/vlad/.ssh/id_rsa.pub') }}"
