- name: Add repo for k8s
  ansible.builtin.yum_repository:
    name: kubernetes
    description: soft for k8s
    baseurl:
    - "{{ kubernetes_repo }}"
    gpgkey:
    - "{{ kubernetes_gpg_key }}"
    enabled: true
    gpgcheck: true
    state: present

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
    update_cache: true
    disable_gpg_check: true # for test only !!!
  notify:
  - start iscsid
  - restart kubelet

- name: Install updated oauthlib for kubernetes compatibility
  ansible.builtin.pip:
    name: "{{ pip_modules }}"
    state: present

- name: Start handler force
  meta: flush_handlers

# - name: disable firewall
#   ansible.builtin.service:
#     name: firewalld
#     state: stopped
#     enabled: false

# - name: Disable SELinux
#   ansible.posix.selinux:
#     state: disabled

- name: Load module
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ modules }}"

- name: Make module persistent
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: "{{ item }}"
    create: true
  loop: "{{ modules }}"

- name: Set "{{ item.key }}" to "{{ item.value}}"
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    state: present
    value: "{{ item.value}}"
    reload: true
  loop: "{{ sysctl_params }}"

- name: Dsable swap
  ansible.builtin.command: swapoff -a
  register: my_output
  changed_when: my_output.rc != 0

- name: Remove swaw from fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: Bashrc edit
  ansible.builtin.blockinfile:
    dest: /home/{{ username }}/.bashrc
    block: |
      source <(kubectl completion bash)
      alias k=kubectl
      complete -o default -F __start_kubectl k
