alloy_version: v1.10.2
alloy_url_download: https://github.com/grafana/alloy/releases/download/{{ alloy_version }}/alloy-linux-amd64.zip
alloy_config_dir: /etc/alloy
alloy_username: alloy
alloy_groups:
  - adm
  - systemd-journal
  - docker
alloy_enable_docker: false
alloy_enable_grafana: false