- name: create folder {{ container_name }}
  ansible.builtin.file:
    path: "{{ sonarqube_docker_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: Copy templates to {{ sonarqube_docker_dir }}
  ansible.builtin.template:
    src: "templates/docker-compose.yaml.j2"
    dest: "{{ sonarqube_docker_dir }}/docker-compose.yaml"
    group: "{{ username }}"
    owner: "{{ username }}"

- name: start docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ sonarqube_docker_dir }}"
    state: present
